import pandas as ps
import time

def analysis(df):
    max_marks = df["Marks"].max()
    min_marks = df["Marks"].min()
    avg_marks = df["Marks"].mean()
    avg_attendance = df["Attendance"].mean()
    avg_hours = df["StudyHours"].mean()
    pass_per = (df["Result"]=="Pass").mean()*100
    fail_per = (df["Result"]=="Fail").mean()*100
    grade_db =  df["Grade"].value_counts()

    print(f"\nAverage Marks: {avg_marks:.2f}")
    time.sleep(1)
    print(f"Highest Marks: {max_marks}")
    time.sleep(1)
    print(f"Lowest Marks: {min_marks}")
    time.sleep(1)
    print(f"Average Attendance: {avg_attendance:.2f}")
    time.sleep(1)
    print(f"Average Study Hours: {avg_hours:.2f}")
    time.sleep(1)
    print(f"Pass Percentage: {pass_per:.2f}%")
    time.sleep(1)
    print(f"Fail Percentage: {fail_per:.2f}%")
    time.sleep(1)
    print("\nGrade Distribution:")
    print(grade_db)

    sorted_marks = df.sort_values(by="Marks",ascending=False)
    time.sleep(1)
    print("\nSorted According to Marks:\n")
    print(sorted_marks)
    sorted_att = df.sort_values(by="Attendance",ascending=False)
    time.sleep(1)
    print("\nSorted According to Attendance\n")
    print(sorted_att)
    sorted_hrs = df.sort_values(by="StudyHours",ascending=False)
    time.sleep(1)
    print("\nSorted According to Study Hours")
    print(sorted_hrs)

    avr_marks = df.groupby("Grade")["Marks"].mean()
    time.sleep(1)
    print("\nAverage marks by grade\n")
    print(avr_marks)
    st_grade = df.groupby("Grade").size()
    time.sleep(1)
    print("\nNumber of Students in each grade\n")
    print(st_grade)
    avr_att = df.groupby("Grade")["Attendance"].mean()
    time.sleep(1)
    print("\nAverage attendance by grade\n")
    print(avr_att)

    time.sleep(1)
    print("\nMean:")
    print(df[["Marks", "Attendance", "StudyHours","Performance Score"]].mean())
    time.sleep(1)
    print("\nMedian:")
    print(df[["Marks", "Attendance", "StudyHours","Performance Score"]].median())
    time.sleep(1)
    print("\nMode:")
    print(df[["Marks", "Attendance", "StudyHours","Performance Score"]].mode())
    time.sleep(1)
    print("\nStandard Deviation:")
    print(df[["Marks", "Attendance", "StudyHours","Performance Score"]].std())
    time.sleep(1)
    print("\nVariance:")
    print(df[["Marks", "Attendance", "StudyHours","Performance Score"]].var())
    time.sleep(1)
    print("\nCorrelation Matrix:")
    print(df[["Marks", "Attendance", "StudyHours","Performance Score"]].corr())
    